# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1444513842);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1444513962);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1444513601);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1444513721);
user_pref("browser.backspace_action", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 307200);
user_pref("browser.display.show_image_placeholders", false);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.defaultenginename", "StartPage - English");
user_pref("browser.search.selectedEngine", "StartPage - English");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.slowStartup.averageTime", 3591);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://www.fsf.org/");
user_pref("browser.startup.homepage_override.buildID", "20150923203929");
user_pref("browser.startup.homepage_override.mstone", "25.7.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":0,\"bookmarks\":0}");
user_pref("browser.urlbar.maxRichResults", -1);
user_pref("extensions.adblockplus.currentVersion", "3.0.3.1");
user_pref("extensions.adblockplus.notificationdata", "{\"lastCheck\":1444514201024,\"softExpiration\":0,\"hardExpiration\":0,\"lastError\":1444514201074,\"downloadStatus\":\"synchronize_invalid_url\"}");
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.bootstrappedAddons", "{\"{016acf6d-e5c0-4768-9376-3763d1ad1978}\":{\"version\":\"3.0.3.1\",\"type\":\"extension\",\"descriptor\":\"/home/holmes/.moonchild productions/pale moon/faz2pd07.default/extensions/{016acf6d-e5c0-4768-9376-3763d1ad1978}.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.7.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1443453575000,\"rdfTime\":1443453575000}}},{\"name\":\"app-profile\",\"addons\":{\"{016acf6d-e5c0-4768-9376-3763d1ad1978}\":{\"descriptor\":\"/home/holmes/.moonchild productions/pale moon/faz2pd07.default/extensions/{016acf6d-e5c0-4768-9376-3763d1ad1978}.xpi\",\"mtime\":1444350286000}}}]");
user_pref("extensions.lastAppVersion", "25.7.1");
user_pref("extensions.lastPlatformVersion", "25.7.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20150923203929");
user_pref("gecko.mstone", "25.7.1");
user_pref("idle.lastDailyNotification", 1444513879);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, windows-1252");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.http.max-connections", 96);
user_pref("network.http.max-connections-per-server", 32);
user_pref("network.http.pipelining.maxrequests", 16);
user_pref("places.database.lastMaintenance", 1444350419);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1443614421);
user_pref("toolkit.startup.last_success", 1444516164);
user_pref("toolkit.telemetry.previousBuildID", "20150824172159");
user_pref("xpinstall.whitelist.add", "");
