#!/bin/bash
#
# Simple bash script to install AUR support
#
# Written by Carl Duff (adapted holmeslinux) 

# Information about this script for the user
echo "${title}Install AUR support${nrml}.

This will install the necessary software to run AUR.

Press ${grnb}[Enter]${nrml} to proceed. You may still cancel the process when prompted."

read
pacman -S yaourt base-devel
read -p $'\n'"Process Complete. Press ${grnb}[Enter]${nrml} to continue."$'\n'
exit 0