#!/bin/bash
#
# Simple bash script to install xdgmenumaker
#
# Written by Carl Duff (adapted holmeslinux) 

# Information about this script for the user
echo "${title}Install xdgmenumaker${nrml}.

This will install the necessary software to create a dynamic menu in JWM.

Press ${grnb}[Enter]${nrml} to proceed. You may still cancel the process when prompted."

read
yaourt -S xdgmenumaker
read -p $'\n'"Process Complete. Press ${grnb}[Enter]${nrml} to continue."$'\n'
exit 0