#!/bin/bash

#  updated on 01.11.2015 16:11:24

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

#########################################################################################
# Design based on IceFox script                                                         #
# Modified, adapted and improved by pekman and excalibur1234                            #
# Some modifications based on the pacli and mhwd-tui (thx @Chrysostomus) made by Holmes #                     
# translation by spylinux					                        #
# Contact and suggestions: pekman@openmailbox.org (JWMconf holmes_holmes@live.com)      #
# Freenode: #manjaropek #manjaro-geek #manjaro			                        #
# Topic discussion 						                        #
#			http://polr.me/Pacli1			                        #
#			http://polr.me/Pacli2					        #
#                       http://bit.ly/1NKCL5e 						#
#			http://bit.ly/1NKCOOp			                        #  
#########################################################################################

function help_text() {
	less 	<<-EOF
JWM (Joe's Window Manager) is a light-weight window manager for the X11 Window System. JWM is written in C and uses only Xlib at a minimum. Because of its small footprint, JWM makes a good window manager for older computers and less powerful systems, such as the Raspberry Pi, though it is perfectly capable of running on modern systems. 
JWM is included in small Linux distributions such as Puppy Linux and Damn Small Linux, and it is available as a separate package in many other distributions.Although JWM does not require them, it can use the following libraries if available:
- libXext for the shape extension;
- libXext for the render extension;
- libXmu for drawing rounded windows (shape extension also needed);
- libXinerama for Xinerama (multi-monitor) support;
- libXpm for XPM backgrounds and icons;
- libjpeg for JPEG backgrounds and icons;
- libpng for PNG backgrounds and icons;
- libRSVG and Cairo for SVG backgrounds and icons;
- libxft for antialiased and true type fonts;
- libfribidi for right-to-left language support.
JWM attempts to conform to the ICCCM and supports both MWM hints and Extended Window Manager Hints (EWMH).See the configuration documentation for comprehensive documentation on configuring JWM. JWM also comes with a manual page: <http://joewing.net/projects/jwm/config.shtml>. 
To exit this information page, press "q".
	EOF
}

# set colors
RED='\e[41m'
BLUE='\e[44m'
ORANGE='\e[46m'
NC='\e[0m'
    while true; do
    clear
    echo ""
    echo -e "                  $NC JWMconf Control Center Shell Configure $NC "
    echo ""
    echo -e "                      $NC ::WARNING! USE WITH CAUTION:: $NC"
    echo -e " ┌─────────────────────────────────────────────────────────────────────────┐"
    echo -e " │  $NC  1  $NC  Refresh Configuration JWM          $NC  2  $NC  Check Error JWM       │"
    echo -e " │  $NC  3  $NC  Edit Menu JWM                      $NC  4  $NC  Edit Panel JWM        │"
    echo -e " │  $NC  5  $NC  Edit Start JWM                     $NC  6  $NC  Edit Theme JWM        │"
    echo -e " │  $NC  7  $NC  Edit Keys JWM                      $NC  8  $NC  Edit Groups JWM       │"
    echo -e " │  $NC  9  $NC  Edit Preferences JWM               $NC 10  $NC  Edit JWMrc            │"
    echo -e " │  $NC 11  $NC  General Commands Manual            $NC 12  $NC  Informations          │"
    echo " └─────────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo " ┌─────────────────────────────────────────────────────────────────────────┐"
    echo -e " │  $NC 13  $NC  Edit Wbar                          $NC 14  $NC  Edit Conky            │"
    echo -e " │  $NC 15  $NC  Edit Dunst                         $NC 16  $NC  Edit Top              │"
    echo -e " │  $NC 17  $NC  Edit Rofi                          $NC 18  $NC  Edit GMRun            │"
    echo " └─────────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo -e "            $NC Select a number and press [Enter]$NC $NC - 0 Exit JWMman$NC"
    echo ""
    read choix
    case $choix in
        1)
            echo
            jwm -restart
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        2)
            echo
            jwm -p
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        3)
            echo
            nano ~/.jwm/menu
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        4)
            echo
            nano ~/.jwm/tray
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        5)
            echo ""
            nano ~/.jwm/start
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        6)
            echo ""
            nano ~/.jwm/theme
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read 
	    ;;
        7)
            echo ""
            nano ~/.jwm/keys
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        8)
            echo ""
            nano ~/.jwm/groups
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        9)
            echo ""
            nano ~/.jwm/preferences
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        10)
            echo ""
            nano ~/.jwmrc
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;

        11)
            echo ""
            man jwm
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;

        12)
            echo
            help_text
            echo
            ;;
        13)
            echo ""
            nano ~/.wbar
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        14)
            echo ""
            nano ~/.conkyrc
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        15)
            echo ""
            nano ~/.config/dunst/dunstrc
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        16)
            echo ""
            nano ~/.toprc
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        17)
            echo ""
            nano ~/.Xresources
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
        18)
            echo ""
            nano ~/.gmrunrc
            echo ""
            echo -e "$NC Operation complete. To return to JWMman press [Enter] $NC"
            read
            ;;
         0)
            clear && exit
            read
            ;;
        *)
            echo -e "$RED Wrong option $NC"
            echo "Wait and try again later..."
            echo ""
            sleep 3
            clear
            ;;
    esac
    done
fi
